# Generated by Django 3.0.4 on 2020-03-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3, verbose_name='Base Currency')),
                ('target_currency', models.CharField(max_length=3, verbose_name='Target Currency')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Rate')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'target_currency'), name='unique_currency_pair'),
        ),
    ]
